import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBarTest from "./components/navigation/NavBarTest";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Asger Kappel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-grey-100-1 bg-cover min-h-screen">
          <NavBarTest />
          <div className="mt-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
